### ISSUE TITLE
Empty result when browse spotify tunigo

### ISSUE THREAD

**Issue by hakanpalm** [trygveaa/mopidy-spotify-tunigo#7]
I have a code like this

    mopidy.library.browse('spotifytunigo:directory').then(function(items){
        ...........

        mopidy.library.browse(items[i].uri).then(function(collection){
       ................
       }
    }

The first browse give me a result like "spotifytunigo:featured", spotifytunigo:toplist .... works fine

Next browse give an empty result, worked without any problem until upgraded to Mopidy 1.1 (yesterday). Is there a connection or is it a Spotify issue?

**Comment by trygveaa** [comment]
Hm, that's weird. It seems to work fine for me.

Does anything appear in Mopidys log when you run this?

**Comment by hakanpalm** [comment]
It seems like I messed up with Debian and pip installations. Uninstall all pip packages, reinstall mopidy and mopidy-spotify-tunigo with apt. Now it's working. Do not know why the fault appears with the upgrade

Sorry to bother you, but it helped me a lot to know that Tunigo would work, thank you for this.
